In [20]:
import os
import pandas as pd

old_run_dir = '../results/run_results/clustering/plot_rbd_cluster-2024-02-26_10-25'
tsne_list = os.path.join(old_run_dir, f"rbd_variants_clustering_esm_blstm_a22073_d22073_o22073_iter0_tsne_coordinates.csv")

data_dir = '../data'
tsne_df = pd.read_csv(tsne_list, sep=',', header=0)
meta_data = os.path.join(data_dir, f"spikeprot0528.clean.uniq.noX.RBD.metadata.tsv")
metadata_df = pd.read_csv(meta_data, sep='\t', header=0, low_memory=False)
metadata_df = metadata_df.rename(columns={'Accession ID': 'seq_id'})
merged_df = pd.merge(tsne_df, metadata_df, on='seq_id', how='left')

copy_merged_df = merged_df.copy()
copy_merged_df['AA Substitutions'].unique()

array(['(Spike_H69del,NS8_Q27stop,NSP3_T183I,Spike_G142del,Spike_K1191N,Spike_T716I,NSP6_S106del,N_R203K,NSP2_G339S,Spike_A570D,NSP8_Q24R,NSP13_K460R,Spike_N501Y,NSP3_I1412T,NS8_R52I,NSP16_L163F,Spike_P681H,Spike_Y144del,Spike_F140del,NSP6_G107del,NSP3_A890D,Spike_D1118H,NSP6_F108del,NS8_Y73C,N_G204R,Spike_V70del,Spike_V143del,NSP7_M75I,Spike_P139del,NSP12_P323L,Spike_Y145del,Spike_D614G,N_D3L,NSP16_K160R,Spike_S982A,Spike_L141del,N_S235F)',
       '(Spike_H69del,NS8_Q27stop,NSP3_T183I,Spike_T716I,NSP3_N1080S,NSP6_S106del,N_R203K,Spike_A570D,NSP13_K460R,NSP4_F17L,Spike_N501Y,NSP3_I1412T,NS8_R52I,Spike_P681H,Spike_Y144del,NSP16_L126F,NSP6_G107del,NSP3_A890D,Spike_D1118H,NSP6_F108del,NS8_Y73C,N_G204R,Spike_V503I,Spike_V70del,NSP12_P323L,Spike_D614G,N_D3L,Spike_S982A,N_S235F)',
       '(NSP2_D449E,Spike_H69del,NS8_Q27stop,NS7a_R80T,NSP3_T183I,Spike_T716I,NSP6_S106del,N_R203K,Spike_A570D,Spike_N501Y,NSP3_I1412T,NS8_R52I,Spike_P681H,Spike_Y144del,NSP6_G107del,NSP3_A890D,Spike_D1118H,NSP6_F108del,NS8_Y73C,N_G204R,Spike_V70del,Spike_A1078V,NSP12_P323L,Spike_D614G,N_D3L,Spike_S982A,N_S235F)',
       ...,
       '(NSP5_P132H,Spike_H69del,NSP3_G489S,Spike_L24del,NSP4_T327I,Spike_S373P,Spike_N969K,Spike_H655Y,N_R203K,Spike_V213G,Spike_G142D,Spike_A27S,Spike_Q954H,N_P13L,Spike_N501Y,Spike_P25del,NS3_T223I,Spike_T19I,M_Q19E,Spike_N440K,NSP4_T492I,M_D3N,Spike_N679K,Spike_N764K,NSP6_G107del,Spike_Y505H,Spike_D796Y,N_G204R,Spike_T478K,N_S413R,M_A63T,Spike_S371F,Spike_T1009I,Spike_K417N,NSP13_R392C,Spike_F486V,Spike_T376A,NSP6_S106del,Spike_G339D,Spike_R408S,NSP14_I42V,NSP4_L264F,Spike_P681H,NSP3_T24I,NSP1_S135R,Spike_S375F,Spike_D405N,Spike_Q498R,Spike_S477N,NSP15_T112I,NSP6_F108del,Spike_E484A,E_T9I,Spike_V70del,Spike_P26del,NSP12_Y521C,NSP12_P323L,Spike_D614G)',
       '(NSP5_P132H,Spike_H69del,NSP3_G489S,Spike_L24del,NSP4_T327I,Spike_S373P,Spike_N969K,Spike_H655Y,N_R203K,Spike_V213G,Spike_G142D,NSP12_N791S,Spike_A27S,Spike_Q954H,N_P13L,Spike_N501Y,Spike_P25del,N_R32del,NS3_T223I,Spike_T19I,M_Q19E,Spike_N440K,NSP4_T492I,Spike_N460K,M_D3N,NSP16_T35I,Spike_N679K,Spike_N764K,NSP6_G107del,Spike_Y505H,Spike_R346I,Spike_D796Y,N_G204R,Spike_T478K,N_S413R,M_A63T,Spike_S371F,Spike_K417N,NSP13_R392C,Spike_F486V,Spike_T376A,NSP6_S106del,Spike_G339D,Spike_R408S,NSP14_I42V,NSP4_L264F,Spike_P681H,NSP3_T24I,N_S33del,NSP1_S135R,Spike_S375F,Spike_D405N,Spike_Q498R,Spike_G446S,Spike_S477N,N_E31del,NSP15_T112I,NSP6_F108del,Spike_E484A,E_T9I,Spike_V70del,Spike_P26del,NSP12_P323L,Spike_D614G,Spike_L452R)',
       '(NSP5_P132H,NSP3_G489S,Spike_L24del,NSP4_T327I,Spike_S373P,Spike_Q493R,Spike_N969K,Spike_H655Y,N_R203K,Spike_V213G,Spike_G142D,Spike_A27S,Spike_Q954H,N_P13L,NSP2_K534R,Spike_N501Y,Spike_P25del,N_R32del,NSP13_T250I,NS3_T223I,Spike_T19I,M_Q19E,Spike_N440K,NSP4_T492I,Spike_N679K,Spike_N764K,NSP6_G107del,Spike_Y505H,Spike_D796Y,N_G204R,Spike_T478K,N_S413R,M_A63T,NSP5_K90R,Spike_S371F,Spike_K417N,NSP13_R392C,Spike_T376A,NSP6_S106del,Spike_G339D,Spike_R408S,NSP2_C33Y,NSP4_L438F,Spike_T29I,NSP14_I42V,NSP4_L264F,Spike_P681H,NSP3_T24I,N_S33del,NSP1_S135R,Spike_S375F,Spike_D405N,Spike_L452M,Spike_Q498R,Spike_S477N,Spike_D936Y,N_E31del,NSP15_T112I,NSP6_F108del,Spike_E484A,E_T9I,Spike_P26del,NSP12_P323L,Spike_D614G,NSP3_P1292S)'],
      dtype=object)

About 118 values are NaN. We need to remove these, however, as they are empty sets. Trying to find the intersection with empty sets will give us an empty set for shared AA Substitutions.

In [21]:
print(len(copy_merged_df[~copy_merged_df['AA Substitutions'].apply(lambda x: isinstance(x, str))]))
copy_merged_df = copy_merged_df.dropna(subset=['AA Substitutions'])
print(len(copy_merged_df[~copy_merged_df['AA Substitutions'].apply(lambda x: isinstance(x, str))]))

118
0

Now, we want to split each entry into a set so that we can find the common and unique AA Substitutions:

In [22]:
copy_merged_df['AA Substitutions Set'] = copy_merged_df['AA Substitutions'].apply(lambda seq: set(seq.strip('()').split(',')))
copy_merged_df['AA Substitutions Set']

0        {Spike_Y145del, NSP6_G107del, NSP3_A890D, Spik...
1        {NSP6_G107del, NSP3_A890D, Spike_D614G, NSP6_F...
2        {NSP6_G107del, NSP3_A890D, Spike_D614G, NSP6_F...
3        {NSP6_G107del, NSP3_A890D, Spike_D614G, NSP6_F...
4        {NSP10_T12I, NSP6_G107del, NSP3_A890D, Spike_D...
                               ...
66214    {Spike_Y145del, Spike_A67V, NSP6_G107del, Spik...
66215    {Spike_Y145del, Spike_A67V, NSP6_G107del, Spik...
66216    {NSP6_G107del, Spike_D614G, Spike_G142D, Spike...
66217    {NSP6_G107del, Spike_D614G, Spike_G142D, Spike...
66218    {Spike_L452M, NSP6_G107del, Spike_D614G, Spike...
Name: AA Substitutions Set, Length: 66101, dtype: object

Find the common mutations across all AA Substitutions:

In [23]:
common_aa_substitutions = set.intersection(*copy_merged_df['AA Substitutions Set'])
print(common_aa_substitutions)

alpha_df = copy_merged_df[copy_merged_df['variant'] == 'Alpha']
common_aa_substitutions = set.intersection(*alpha_df['AA Substitutions Set'])
print(common_aa_substitutions)

delta_df = copy_merged_df[copy_merged_df['variant'] == 'Delta']
common_aa_substitutions = set.intersection(*delta_df['AA Substitutions Set'])
print(common_aa_substitutions)

omicron_df = copy_merged_df[copy_merged_df['variant'] == 'Omicron']
common_aa_substitutions = set.intersection(*omicron_df['AA Substitutions Set'])
print(common_aa_substitutions)

set()
set()
set()
set()

Well, still nothing common between all. Let's try to look at the percentages of entries in which each AA Substitution occurs instead.

In [49]:
from collections import Counter
import pandas as pd

# Flatten the list of all substitutions across all sequences
all_substitutions = [sub for substitutions in copy_merged_df['AA Substitutions Set'] for sub in substitutions]

# Count occurrences of each substitution
substitution_counts = Counter(all_substitutions)

# Calculate the total number of sequences
total_sequences = len(copy_merged_df)

# Calculate the percentage for each substitution
substitution_percentage = {sub: (count / total_sequences) * 100 for sub, count in substitution_counts.items()}

# Convert to a DataFrame for better readability
substitution_percentage_df = pd.DataFrame(list(substitution_percentage.items()), columns=['Substitution', 'Percentage'])

# Sort by percentage
substitution_percentage_df = substitution_percentage_df.sort_values(by='Percentage', ascending=False)

# Reset index
substitution_percentage_df.reset_index(drop=True, inplace=True)
substitution_percentage_df

      Substitution  Percentage
0      Spike_D614G   99.579431
1      NSP12_P323L   98.069621
2      Spike_P681H   65.177531
3      Spike_N501Y   65.101890
4      Spike_T478K   65.000529
...            ...         ...
41324   NSP2_A247C    0.001513
41325   NSP2_E197Q    0.001513
41326   NSP2_C164V    0.001513
41327   NSP2_Q346E    0.001513
41328  NSP12_F812V    0.001513

[41329 rows x 2 columns]

In [74]:
# Now, as a function:

import pandas as pd
from collections import Counter

def calc_substitution_perc(df_column, cutoff_perc=85):
    all_substitutions = [sub for substitutions in df_column for sub in substitutions]
    substitution_counts = Counter(all_substitutions)
    total_sequences = len(df_column)
    substitution_percentage = {sub: (count / total_sequences) * 100 for sub, count in substitution_counts.items()}
    substitution_percentage_df = pd.DataFrame(list(substitution_percentage.items()), columns=['Substitution', 'Percentage'])
    substitution_percentage_df = substitution_percentage_df.sort_values(by='Percentage', ascending=False)
    substitution_percentage_df.reset_index(drop=True, inplace=True)

    # Filter out substitutions below the cutoff percentage
    filtered_df = substitution_percentage_df[substitution_percentage_df['Percentage'] >= cutoff_perc]
    
    return filtered_df

calc_substitution_perc(copy_merged_df['AA Substitutions Set'], cutoff_perc=0)

      Substitution  Percentage
0      Spike_D614G   99.579431
1      NSP12_P323L   98.069621
2      Spike_P681H   65.177531
3      Spike_N501Y   65.101890
4      Spike_T478K   65.000529
...            ...         ...
41324   NSP2_A247C    0.001513
41325   NSP2_E197Q    0.001513
41326   NSP2_C164V    0.001513
41327   NSP2_Q346E    0.001513
41328  NSP12_F812V    0.001513

[41329 rows x 2 columns]

Now compare per variant:

In [81]:
variant_list = copy_merged_df['variant'].unique()
variant_dfs = {}

for variant in variant_list:
    variant_df = copy_merged_df[copy_merged_df['variant'] == variant]
    sub_perc_df = calc_substitution_perc(variant_df['AA Substitutions Set'], cutoff_perc=0)
    variant_dfs[variant] = sub_perc_df

for variant, df in variant_dfs.items():
    print(f"\n{variant}")
    print(df)

Alpha
       Substitution  Percentage
0       Spike_D614G   99.437463
1       NSP12_P323L   99.346731
2        NSP3_T183I   98.697999
3           N_S235F   98.398585
4        NSP3_A890D   98.366828
...             ...         ...
23401    NSP3_A256T    0.004537
23402     NS3_Y184H    0.004537
23403   Spike_Y674C    0.004537
23404  Spike_N1108K    0.004537
23405   Spike_S680T    0.004537

[23406 rows x 2 columns]

Delta
      Substitution  Percentage
0      Spike_D614G   99.718859
1      Spike_T478K   99.165646
2      Spike_P681R   98.902644
3      Spike_L452R   98.553485
4         NS3_S26L   98.453725
...            ...         ...
24954    NSP3_Y87G    0.004535
24955   NSP15_T48C    0.004535
24956   NSP15_L75W    0.004535
24957  NSP15_T112R    0.004535
24958    NSP3_D59A    0.004535

[24959 rows x 2 columns]

Omicron
      Substitution  Percentage
0      Spike_D614G   99.581913
1      Spike_N679K   98.836628
2      Spike_H655Y   98.827539
3      Spike_D796Y   98.563963
4      Spike_P681H   97.823222
...            ...         ...
19923   NSP4_G288Q    0.004544
19924   NSP4_V294T    0.004544
19925   NSP4_A298F    0.004544
19926   NSP4_T295W    0.004544
19927  NSP12_F812V    0.004544

[19928 rows x 2 columns]

Let's take a look at the 13 omicron clusters from earlier. Like what we did with pango lineage before, let's try with AA substitutions.

In [82]:
cluster_aa_data = {}

for i in range(len(omicron_cluster_ranges)):
    # Filter data for the current cluster based on DIM_1 and DIM_2 coordinates
    cluster = omicron_cluster_ranges[i]
    cluster_df = omicron_df[
        (omicron_df['DIM_1'] >= cluster['DIM_1_LEFT']) &
        (omicron_df['DIM_1'] <= cluster['DIM_1_RIGHT']) &
        (omicron_df['DIM_2'] <= cluster['DIM_2_TOP']) &
        (omicron_df['DIM_2'] >= cluster['DIM_2_BOTTOM']) 
    ]
    cluster_aa_substitutions = {}
    sub_perc_df = calc_substitution_perc(cluster_df['AA Substitutions Set'], cutoff_perc=0)
    cluster_aa_data[f"Cluster {i+1}"] = sub_perc_df 
    
    print(f"Omicron Cluster {i+1}:\n{sub_perc_df}\n")

Omicron Cluster 1:
      Substitution  Percentage
0      Spike_S373P  100.000000
1      Spike_H655Y   99.855908
2      Spike_S375F   99.855908
3      Spike_D614G   99.567723
4      Spike_N501Y   99.567723
...            ...         ...
1739    NSP3_A534V    0.144092
1740     NS7a_S36P    0.144092
1741   Spike_P272S    0.144092
1742  Spike_S1170F    0.144092
1743      NSP6_A2T    0.144092

[1744 rows x 2 columns]

Omicron Cluster 2:
     Substitution  Percentage
0     Spike_Y505H  100.000000
1     Spike_D614G  100.000000
2     Spike_N501Y   99.861207
3     Spike_S477N   99.722415
4     Spike_T478K   99.583622
...           ...         ...
3173    NSP1_D33N    0.069396
3174     NS3_L95F    0.069396
3175  NSP12_K281E    0.069396
3176  Spike_L249S    0.069396
3177   NSP14_H26Y    0.069396

[3178 rows x 2 columns]

Omicron Cluster 3:
     Substitution  Percentage
0     Spike_N501Y   99.934598
1     Spike_Y505H   99.934598
2     Spike_D614G   99.869196
3     Spike_S373P   99.803793
4     Spike_D405N   99.803793
...           ...         ...
3295  NSP3_V1777I    0.065402
3296  NSP12_T908N    0.065402
3297  Spike_P862S    0.065402
3298  Spike_G252V    0.065402
3299   NSP16_G77R    0.065402

[3300 rows x 2 columns]

Omicron Cluster 4:
     Substitution  Percentage
0     Spike_D796Y  100.000000
1     Spike_H655Y  100.000000
2     Spike_S375F  100.000000
3     Spike_Y505H  100.000000
4     Spike_N501Y  100.000000
...           ...         ...
1761  Spike_P322S    0.182815
1762  Spike_H625R    0.182815
1763  Spike_A831V    0.182815
1764   NSP4_I383V    0.182815
1765  Spike_F855S    0.182815

[1766 rows x 2 columns]

Omicron Cluster 5:
      Substitution  Percentage
0      Spike_N679K  100.000000
1      Spike_P681H  100.000000
2      Spike_H655Y   99.815838
3      Spike_D796Y   99.631676
4      Spike_N764K   99.631676
...            ...         ...
1571  Spike_A1080S    0.184162
1572    NSP4_E425Q    0.184162
1573    NSP12_A16V    0.184162
1574   Spike_I197V    0.184162
1575   Spike_I670V    0.184162

[1576 rows x 2 columns]

Omicron Cluster 6:
     Substitution  Percentage
0     Spike_N501Y  100.000000
1     Spike_Q498R  100.000000
2     Spike_Y505H   99.776786
3     Spike_S477N   99.553571
4     Spike_H655Y   99.553571
...           ...         ...
1229    NSP7_S24L    0.223214
1230  NSP3_G1451D    0.223214
1231   NSP8_T123I    0.223214
1232   NSP2_L350P    0.223214
1233  NSP13_L581F    0.223214

[1234 rows x 2 columns]

Omicron Cluster 7:
      Substitution  Percentage
0      Spike_N501Y  100.000000
1      Spike_D405N  100.000000
2      Spike_S371F  100.000000
3      Spike_Q498R  100.000000
4      Spike_T478K  100.000000
...            ...         ...
2576   NSP12_R279K    0.093371
2577    NSP13_K76N    0.093371
2578  Spike_D1260Y    0.093371
2579     NSP4_H31Y    0.093371
2580   Spike_A846S    0.093371

[2581 rows x 2 columns]

Omicron Cluster 8:
      Substitution  Percentage
0      Spike_S477N  100.000000
1      Spike_Q498R  100.000000
2      Spike_T376A  100.000000
3      Spike_Q493R  100.000000
4      Spike_E484A  100.000000
...            ...         ...
3604   Spike_K147I    0.058858
3605    NSP4_S481L    0.058858
3606    NSP3_L710I    0.058858
3607  Spike_A1087V    0.058858
3608    NSP8_T145M    0.058858

[3609 rows x 2 columns]

Omicron Cluster 9:
     Substitution  Percentage
0     Spike_Y505H  100.000000
1     Spike_Q493R  100.000000
2     Spike_Q498R  100.000000
3     Spike_N501Y  100.000000
4     Spike_N440K   99.919094
...           ...         ...
2973  NSP13_V372G    0.080906
2974  NSP3_S1314G    0.080906
2975  NSP12_A379T    0.080906
2976  Spike_L216I    0.080906
2977  Spike_T638I    0.080906

[2978 rows x 2 columns]

Omicron Cluster 10:
     Substitution  Percentage
0     Spike_G496S  100.000000
1     Spike_K417N  100.000000
2     Spike_Q493R  100.000000
3     Spike_Y505H  100.000000
4     Spike_N440K  100.000000
...           ...         ...
2955   NSP15_A92P    0.085543
2956   NSP6_V190F    0.085543
2957  Spike_Q675R    0.085543
2958  Spike_I997V    0.085543
2959   NSP3_K837N    0.085543

[2960 rows x 2 columns]

Omicron Cluster 11:
     Substitution  Percentage
0     Spike_N440K  100.000000
1     Spike_L452R  100.000000
2     Spike_T376A  100.000000
3     Spike_Q498R  100.000000
4     Spike_S375F  100.000000
...           ...         ...
2289    NSP1_P80E    0.120192
2290    NSP1_T78M    0.120192
2291    NSP1_Y68M    0.120192
2292    NSP1_Q66S    0.120192
2293  Spike_S221L    0.120192

[2294 rows x 2 columns]

Omicron Cluster 12:
      Substitution  Percentage
0      Spike_S373P    100.0000
1      Spike_L452R    100.0000
2       NSP4_T492I    100.0000
3       NSP5_P132H    100.0000
4      Spike_N764K     99.7543
...            ...         ...
1144     NS3_A103S      0.2457
1145  NS7a_F101del      0.2457
1146   NS7a_P99del      0.2457
1147       N_S190R      0.2457
1148   Spike_G842S      0.2457

[1149 rows x 2 columns]

Omicron Cluster 13:
     Substitution  Percentage
0     Spike_E484A   100.00000
1     Spike_D405N   100.00000
2     Spike_S371F   100.00000
3     Spike_Q498R   100.00000
4     Spike_T478K   100.00000
...           ...         ...
5993   NSP2_A411S     0.03199
5994  Spike_G946R     0.03199
5995   NSP8_M129K     0.03199
5996   NSP5_A191V     0.03199
5997  NSP3_Y1041H     0.03199

[5998 rows x 2 columns]

Let's try to specify spike AA substitutions, since we used the spike protein sequences for plotting. We'll do all the steps above here, but for spike protein specifically:

In [24]:
# Function to filter for spike protein substitutions
copy_merged_df['Spike Substitutions Set'] = copy_merged_df['AA Substitutions Set'].apply(
    lambda substitutions_set: {sub for sub in substitutions_set if sub.startswith('Spike_')}
)
copy_merged_df['Spike Substitutions Set']

0        {Spike_Y145del, Spike_D614G, Spike_A570D, Spik...
1        {Spike_A570D, Spike_D614G, Spike_H69del, Spike...
2        {Spike_A570D, Spike_D614G, Spike_H69del, Spike...
3        {Spike_A570D, Spike_D614G, Spike_H69del, Spike...
4        {Spike_A570D, Spike_D614G, Spike_H69del, Spike...
                               ...
66214    {Spike_Y145del, Spike_A67V, Spike_D614G, Spike...
66215    {Spike_Y145del, Spike_A67V, Spike_D614G, Spike...
66216    {Spike_D614G, Spike_G142D, Spike_A27S, Spike_P...
66217    {Spike_D614G, Spike_Q954H, Spike_G142D, Spike_...
66218    {Spike_L452M, Spike_D614G, Spike_G142D, Spike_...
Name: Spike Substitutions Set, Length: 66101, dtype: object

In [25]:
common_spike_aa_substitutions = set.intersection(*copy_merged_df['Spike Substitutions Set'])
print(common_spike_aa_substitutions )

alpha_df = copy_merged_df[copy_merged_df['variant'] == 'Alpha']
common_spike_aa_substitutions  = set.intersection(*alpha_df['Spike Substitutions Set'])
print(common_spike_aa_substitutions )

delta_df = copy_merged_df[copy_merged_df['variant'] == 'Delta']
common_spike_aa_substitutions  = set.intersection(*delta_df['Spike Substitutions Set'])
print(common_spike_aa_substitutions )

omicron_df = copy_merged_df[copy_merged_df['variant'] == 'Omicron']
common_spike_aa_substitutions = set.intersection(*omicron_df['Spike Substitutions Set'])
print(common_spike_aa_substitutions )

set()
set()
set()
set()

In [75]:
# Whole, spike protein
calc_substitution_perc(copy_merged_df['Spike Substitutions Set'], cutoff_perc=0)

      Substitution  Percentage
0      Spike_D614G   99.579431
1      Spike_P681H   65.177531
2      Spike_N501Y   65.101890
3      Spike_T478K   65.000529
4      Spike_G142D   55.566482
...            ...         ...
8382   Spike_A694G    0.001513
8383  Spike_E1031D    0.001513
8384   Spike_Q271P    0.001513
8385   Spike_C488W    0.001513
8386   Spike_L996F    0.001513

[8387 rows x 2 columns]

In [80]:
# Variant, spike protein
variant_list = copy_merged_df['variant'].unique()
variant_dfs = {}

for variant in variant_list:
    variant_df = copy_merged_df[copy_merged_df['variant'] == variant]
    sub_perc_df = calc_substitution_perc(variant_df['Spike Substitutions Set'], cutoff_perc=0)
    variant_dfs[variant] = sub_perc_df

for variant, df in variant_dfs.items():
    print(f"\n{variant}")
    print(df)

Alpha
       Substitution  Percentage
0       Spike_D614G   99.437463
1      Spike_D1118H   98.085560
2       Spike_S982A   97.895023
3       Spike_N501Y   97.876877
4       Spike_T716I   97.767999
...             ...         ...
5616  Spike_F238del    0.004537
5617  Spike_G252del    0.004537
5618  Spike_I233del    0.004537
5619  Spike_S221del    0.004537
5620    Spike_S680T    0.004537

[5621 rows x 2 columns]

Delta
       Substitution  Percentage
0       Spike_D614G   99.718859
1       Spike_T478K   99.165646
2       Spike_P681R   98.902644
3       Spike_L452R   98.553485
4        Spike_T19R   98.095497
...             ...         ...
5433  Spike_N764del    0.004535
5434  Spike_N703del    0.004535
5435    Spike_G889L    0.004535
5436    Spike_D737Q    0.004535
5437    Spike_S443C    0.004535

[5438 rows x 2 columns]

Omicron
     Substitution  Percentage
0     Spike_D614G   99.581913
1     Spike_N679K   98.836628
2     Spike_H655Y   98.827539
3     Spike_D796Y   98.563963
4     Spike_P681H   97.823222
...           ...         ...
5190  Spike_P225L    0.004544
5191  Spike_D950S    0.004544
5192  Spike_L948T    0.004544
5193  Spike_Q949S    0.004544
5194  Spike_L293H    0.004544

[5195 rows x 2 columns]

In [83]:
# 13 clusters, spike protein
cluster_aa_data = {}

for i in range(len(omicron_cluster_ranges)):
    # Filter data for the current cluster based on DIM_1 and DIM_2 coordinates
    cluster = omicron_cluster_ranges[i]
    cluster_df = omicron_df[
        (omicron_df['DIM_1'] >= cluster['DIM_1_LEFT']) &
        (omicron_df['DIM_1'] <= cluster['DIM_1_RIGHT']) &
        (omicron_df['DIM_2'] <= cluster['DIM_2_TOP']) &
        (omicron_df['DIM_2'] >= cluster['DIM_2_BOTTOM']) 
    ]
    cluster_aa_substitutions = {}
    sub_perc_df = calc_substitution_perc(cluster_df['Spike Substitutions Set'], cutoff_perc=0)
    cluster_aa_data[f"Cluster {i+1}"] = sub_perc_df 
    
    print(f"Omicron Cluster {i+1}:\n{sub_perc_df}\n")

Omicron Cluster 1:
     Substitution  Percentage
0     Spike_S373P  100.000000
1     Spike_H655Y   99.855908
2     Spike_S375F   99.855908
3     Spike_D614G   99.567723
4     Spike_N501Y   99.567723
..            ...         ...
652   Spike_L455S    0.144092
653  Spike_Y1209H    0.144092
654   Spike_K202R    0.144092
655   Spike_R765L    0.144092
656   Spike_T874I    0.144092

[657 rows x 2 columns]

Omicron Cluster 2:
      Substitution  Percentage
0      Spike_D614G  100.000000
1      Spike_Y505H  100.000000
2      Spike_N501Y   99.861207
3      Spike_S477N   99.722415
4      Spike_T478K   99.583622
...            ...         ...
1052   Spike_N657K    0.069396
1053   Spike_N925S    0.069396
1054   Spike_S155N    0.069396
1055  Spike_D1127V    0.069396
1056    Spike_P85Q    0.069396

[1057 rows x 2 columns]

Omicron Cluster 3:
      Substitution  Percentage
0      Spike_Y505H   99.934598
1      Spike_N501Y   99.934598
2      Spike_D614G   99.869196
3      Spike_D405N   99.803793
4      Spike_Q498R   99.803793
...            ...         ...
1114   Spike_A411S    0.065402
1115    Spike_W64L    0.065402
1116  Spike_R1107T    0.065402
1117  Spike_C1235F    0.065402
1118  Spike_D1153V    0.065402

[1119 rows x 2 columns]

Omicron Cluster 4:
     Substitution  Percentage
0     Spike_N501Y  100.000000
1     Spike_Y505H  100.000000
2     Spike_S375F  100.000000
3     Spike_H655Y  100.000000
4     Spike_D796Y  100.000000
..            ...         ...
564   Spike_H625R    0.182815
565    Spike_V16F    0.182815
566  Spike_S1097L    0.182815
567   Spike_E324A    0.182815
568   Spike_F855S    0.182815

[569 rows x 2 columns]

Omicron Cluster 5:
     Substitution  Percentage
0     Spike_P681H  100.000000
1     Spike_N679K  100.000000
2     Spike_H655Y   99.815838
3     Spike_D796Y   99.631676
4     Spike_N764K   99.631676
..            ...         ...
514   Spike_W152L    0.184162
515  Spike_C1250Y    0.184162
516  Spike_N1125S    0.184162
517  Spike_A1080S    0.184162
518   Spike_I670V    0.184162

[519 rows x 2 columns]

Omicron Cluster 6:
     Substitution  Percentage
0     Spike_N501Y  100.000000
1     Spike_Q498R  100.000000
2     Spike_Y505H   99.776786
3     Spike_N679K   99.553571
4     Spike_S477N   99.553571
..            ...         ...
413  Spike_D1041G    0.223214
414   Spike_E516Q    0.223214
415   Spike_P330H    0.223214
416   Spike_S884F    0.223214
417   Spike_A411S    0.223214

[418 rows x 2 columns]

Omicron Cluster 7:
     Substitution  Percentage
0     Spike_S373P  100.000000
1     Spike_T478K  100.000000
2     Spike_Q498R  100.000000
3     Spike_D405N  100.000000
4     Spike_S371F  100.000000
..            ...         ...
965  Spike_K1255R    0.093371
966   Spike_V511I    0.093371
967    Spike_T22I    0.093371
968  Spike_D1260Y    0.093371
969   Spike_A846S    0.093371

[970 rows x 2 columns]

Omicron Cluster 8:
      Substitution  Percentage
0      Spike_K417N  100.000000
1      Spike_N440K  100.000000
2      Spike_G339D  100.000000
3      Spike_S373P  100.000000
4      Spike_D405N  100.000000
...            ...         ...
1406  Spike_E1150A    0.058858
1407   Spike_V642F    0.058858
1408  Spike_S1261P    0.058858
1409  Spike_T1120I    0.058858
1410   Spike_L293H    0.058858

[1411 rows x 2 columns]

Omicron Cluster 9:
     Substitution  Percentage
0     Spike_Q498R  100.000000
1     Spike_N501Y  100.000000
2     Spike_Y505H  100.000000
3     Spike_Q493R  100.000000
4     Spike_T478K   99.919094
...           ...         ...
1258   Spike_K97Q    0.080906
1259  Spike_S967G    0.080906
1260  Spike_K150N    0.080906
1261  Spike_S730Y    0.080906
1262  Spike_T638I    0.080906

[1263 rows x 2 columns]

Omicron Cluster 10:
     Substitution  Percentage
0     Spike_N440K  100.000000
1     Spike_T478K  100.000000
2     Spike_Q498R  100.000000
3     Spike_G496S  100.000000
4     Spike_Y505H  100.000000
...           ...         ...
1218  Spike_R682T    0.085543
1219  Spike_A766V    0.085543
1220  Spike_P715A    0.085543
1221  Spike_G667T    0.085543
1222   Spike_H49D    0.085543

[1223 rows x 2 columns]

Omicron Cluster 11:
     Substitution  Percentage
0     Spike_T376A  100.000000
1     Spike_N440K  100.000000
2     Spike_L452R  100.000000
3     Spike_Q498R  100.000000
4     Spike_S375F  100.000000
..            ...         ...
834  Spike_N1187D    0.120192
835   Spike_V159I    0.120192
836  Spike_T1009N    0.120192
837   Spike_A163T    0.120192
838   Spike_S221L    0.120192

[839 rows x 2 columns]

Omicron Cluster 12:
     Substitution  Percentage
0     Spike_L452R    100.0000
1     Spike_S373P    100.0000
2     Spike_D614G     99.7543
3     Spike_S371F     99.7543
4     Spike_N764K     99.7543
..            ...         ...
424   Spike_M177V      0.2457
425  Spike_N1023S      0.2457
426    Spike_R78K      0.2457
427   Spike_T250P      0.2457
428   Spike_G842S      0.2457

[429 rows x 2 columns]

Omicron Cluster 13:
      Substitution  Percentage
0      Spike_N501Y   100.00000
1      Spike_T478K   100.00000
2      Spike_L452R   100.00000
3      Spike_Q498R   100.00000
4      Spike_S371F   100.00000
...            ...         ...
2034   Spike_E156Q     0.03199
2035   Spike_S112A     0.03199
2036  Spike_C1247S     0.03199
2037   Spike_S750I     0.03199
2038   Spike_K444N     0.03199

[2039 rows x 2 columns]

Let's introduce an 80% cutoff, and save the results. We'll focus on the 1st 3 clusters:

In [91]:
# 13 clusters, spike protein
cluster_aa_data = {}

for i in range(len(omicron_cluster_ranges)):
    # Filter data for the current cluster based on DIM_1 and DIM_2 coordinates
    cluster = omicron_cluster_ranges[i]
    cluster_df = omicron_df[
        (omicron_df['DIM_1'] >= cluster['DIM_1_LEFT']) &
        (omicron_df['DIM_1'] <= cluster['DIM_1_RIGHT']) &
        (omicron_df['DIM_2'] <= cluster['DIM_2_TOP']) &
        (omicron_df['DIM_2'] >= cluster['DIM_2_BOTTOM']) 
    ]
    cluster_aa_substitutions = {}
    sub_perc_df = calc_substitution_perc(cluster_df['Spike Substitutions Set'], cutoff_perc=80)
    cluster_aa_data[f"Cluster {i+1}"] = sub_perc_df 
    
    print(f"Omicron Cluster {i+1}:\n{sub_perc_df}\n")

Omicron Cluster 1:
    Substitution  Percentage
0    Spike_S373P  100.000000
1    Spike_H655Y   99.855908
2    Spike_S375F   99.855908
3    Spike_D614G   99.567723
4    Spike_N501Y   99.567723
5    Spike_N679K   99.567723
6    Spike_Y505H   99.279539
7    Spike_D796Y   99.279539
8    Spike_P681H   99.135447
9    Spike_S477N   99.135447
10   Spike_Q498R   98.847262
11   Spike_T376A   98.703170
12   Spike_N969K   98.703170
13   Spike_Q954H   98.703170
14   Spike_N764K   98.703170
15   Spike_G339D   98.559078
16   Spike_T478K   98.414986
17   Spike_S371F   98.414986
18   Spike_D405N   98.126801
19   Spike_G142D   97.838617
20   Spike_V213G   97.838617
21   Spike_E484A   97.406340
22   Spike_K417N   97.118156
23  Spike_P26del   96.974063
24  Spike_L24del   96.974063
25  Spike_P25del   96.974063
26    Spike_A27S   96.829971
27    Spike_T19I   96.397695
28   Spike_R408S   92.363112
29   Spike_N440K   91.930836
30   Spike_Q493R   91.642651
31   Spike_L452Q   86.167147
32   Spike_S704L   82.853026

Omicron Cluster 2:
    Substitution  Percentage
0    Spike_D614G  100.000000
1    Spike_Y505H  100.000000
2    Spike_N501Y   99.861207
3    Spike_S477N   99.722415
4    Spike_T478K   99.583622
5    Spike_N679K   99.514226
6    Spike_H655Y   99.514226
7    Spike_G339D   99.514226
8    Spike_E484A   99.444830
9    Spike_S373P   99.167245
10   Spike_D405N   99.097849
11   Spike_N764K   99.028452
12   Spike_D796Y   98.959056
13   Spike_L452R   98.889660
14   Spike_P681H   98.889660
15   Spike_Q498R   98.681471
16   Spike_S375F   98.542679
17   Spike_T376A   98.334490
18  Spike_P25del   98.195697
19  Spike_P26del   98.195697
20   Spike_V213G   98.195697
21   Spike_F486V   98.126301
22   Spike_K417N   98.126301
23   Spike_S371F   97.918112
24  Spike_L24del   97.848716
25    Spike_A27S   97.640527
26   Spike_G142D   97.501735
27  Spike_V70del   97.362942
28  Spike_H69del   97.293546
29    Spike_T19I   96.807772
30   Spike_N440K   96.599584
31   Spike_N969K   95.697432
32   Spike_Q954H   95.350451
33   Spike_R408S   94.517696
34   Spike_R346T   89.659958

Omicron Cluster 3:
    Substitution  Percentage
0    Spike_Y505H   99.934598
1    Spike_N501Y   99.934598
2    Spike_D614G   99.869196
3    Spike_D405N   99.803793
4    Spike_Q498R   99.803793
5    Spike_S373P   99.803793
6    Spike_L452R   99.803793
7    Spike_N440K   99.738391
8    Spike_S375F   99.607587
9    Spike_E484A   99.542184
10   Spike_N764K   99.476782
11   Spike_D796Y   99.476782
12   Spike_H655Y   99.411380
13   Spike_N679K   99.411380
14   Spike_T376A   99.411380
15   Spike_S477N   99.149771
16   Spike_P681H   98.953564
17   Spike_V213G   98.757358
18  Spike_P26del   98.757358
19  Spike_P25del   98.757358
20   Spike_G339D   98.757358
21   Spike_S371F   98.757358
22   Spike_T478K   98.691956
23  Spike_L24del   98.561151
24    Spike_A27S   98.495749
25   Spike_F486V   98.103336
26  Spike_V70del   97.972531
27    Spike_T19I   97.907129
28  Spike_H69del   97.907129
29   Spike_R346T   97.841727
30   Spike_G142D   96.991498
31   Spike_N969K   96.468280
32   Spike_N460K   96.272073
33   Spike_Q954H   95.618051
34   Spike_K444T   95.356442
35   Spike_R408S   95.029431
36   Spike_K417N   94.113800

Omicron Cluster 4:
    Substitution  Percentage
0    Spike_N501Y  100.000000
1    Spike_Y505H  100.000000
2    Spike_S375F  100.000000
3    Spike_H655Y  100.000000
4    Spike_D796Y  100.000000
5    Spike_D614G   99.817185
6    Spike_Q498R   99.817185
7    Spike_S373P   99.817185
8    Spike_E484A   99.634369
9    Spike_T478K   99.634369
10   Spike_N440K   99.634369
11   Spike_N679K   99.451554
12   Spike_S477N   99.451554
13   Spike_D405N   99.451554
14  Spike_P26del   99.268739
15  Spike_P25del   99.268739
16   Spike_N764K   99.268739
17   Spike_T376A   99.268739
18   Spike_P681H   99.085923
19   Spike_N460K   98.903108
20   Spike_L452R   98.720293
21  Spike_L24del   98.720293
22    Spike_A27S   98.720293
23   Spike_G339H   98.537477
24    Spike_T19I   98.354662
25   Spike_R408S   98.354662
26   Spike_S371F   98.171846
27   Spike_K417N   97.806216
28   Spike_V213G   97.257770
29   Spike_G446S   97.074954
30   Spike_G142D   96.709324
31   Spike_G257S   96.343693
32   Spike_I210V   95.978062
33   Spike_F157L   95.612431
34   Spike_K147E   95.429616
35   Spike_W152R   95.429616
36   Spike_N969K   94.332724
37   Spike_Q954H   94.332724
38   Spike_R346T   93.967093
39   Spike_F486S   81.535649

Omicron Cluster 5:
    Substitution  Percentage
0    Spike_P681H  100.000000
1    Spike_N679K  100.000000
2    Spike_H655Y   99.815838
3    Spike_D796Y   99.631676
4    Spike_N764K   99.631676
5    Spike_D614G   99.447514
6    Spike_S373P   99.263352
7    Spike_S375F   99.079190
8    Spike_N501Y   98.895028
9    Spike_D405N   98.526703
10   Spike_Y505H   98.526703
11   Spike_T376A   98.342541
12   Spike_S371F   98.342541
13   Spike_Q498R   98.342541
14   Spike_K417N   97.974217
15   Spike_G339H   97.974217
16  Spike_P26del   97.421731
17   Spike_N440K   97.421731
18  Spike_P25del   97.421731
19   Spike_N460K   97.237569
20  Spike_L24del   97.053407
21    Spike_A27S   97.053407
22   Spike_S477N   96.685083
23   Spike_G446S   96.685083
24    Spike_T19I   96.500921
25   Spike_N969K   96.500921
26   Spike_E484A   96.500921
27   Spike_Q954H   96.316759
28   Spike_K356T   96.132597
29   Spike_G142D   95.027624
30   Spike_T478K   94.475138
31   Spike_V213G   93.738490
32   Spike_I210V   93.554328
33   Spike_R408S   93.001842
34   Spike_G257S   90.423573
35   Spike_F157L   90.423573
36   Spike_W152R   89.686924
37   Spike_K147E   89.502762
38   Spike_F490S   88.950276
39   Spike_R346T   86.740331

Omicron Cluster 6:
     Substitution  Percentage
0     Spike_N501Y  100.000000
1     Spike_Q498R  100.000000
2     Spike_Y505H   99.776786
3     Spike_N679K   99.553571
4     Spike_S477N   99.553571
5     Spike_H655Y   99.553571
6     Spike_P681H   99.330357
7     Spike_T478K   99.330357
8     Spike_F490S   99.330357
9     Spike_D614G   99.330357
10    Spike_D405N   99.330357
11    Spike_N764K   99.107143
12    Spike_N460K   99.107143
13    Spike_E484A   98.883929
14    Spike_N440K   98.660714
15    Spike_G446S   98.437500
16    Spike_S371F   98.214286
17    Spike_D796Y   98.214286
18    Spike_S373P   97.767857
19    Spike_T376A   97.098214
20    Spike_N969K   97.098214
21    Spike_Q954H   97.098214
22    Spike_S375F   97.098214
23    Spike_R346T   96.875000
24    Spike_G339H   96.651786
25    Spike_G142D   95.535714
26    Spike_Q183E   94.866071
27     Spike_A27S   94.642857
28   Spike_P25del   94.642857
29   Spike_L24del   94.642857
30   Spike_P26del   94.642857
31    Spike_L368I   94.419643
32    Spike_V445P   94.419643
33     Spike_V83A   93.973214
34     Spike_T19I   93.526786
35    Spike_V213E   93.303571
36    Spike_F486S   93.080357
37    Spike_R408S   92.857143
38    Spike_K417N   90.848214
39  Spike_Y144del   89.732143
40    Spike_H146Q   87.276786

Omicron Cluster 7:
     Substitution  Percentage
0     Spike_S373P  100.000000
1     Spike_T478K  100.000000
2     Spike_Q498R  100.000000
3     Spike_D405N  100.000000
4     Spike_S371F  100.000000
5     Spike_S375F  100.000000
6     Spike_Y505H  100.000000
7     Spike_N501Y  100.000000
8     Spike_N460K   99.906629
9     Spike_R346T   99.906629
10    Spike_S477N   99.906629
11    Spike_G339H   99.906629
12    Spike_T376A   99.906629
13    Spike_P681H   99.813259
14    Spike_H655Y   99.813259
15    Spike_N440K   99.813259
16    Spike_E484A   99.813259
17    Spike_N679K   99.719888
18    Spike_D614G   99.626517
19    Spike_N764K   99.533147
20   Spike_P25del   99.533147
21   Spike_P26del   99.439776
22    Spike_G446S   99.439776
23    Spike_L368I   99.439776
24    Spike_K417N   99.346405
25    Spike_D796Y   99.253035
26    Spike_V445P   99.253035
27     Spike_A27S   99.066293
28   Spike_L24del   99.066293
29    Spike_F490S   98.972923
30    Spike_F486P   98.692810
31    Spike_V213E   98.506069
32     Spike_T19I   98.412698
33     Spike_V83A   98.132586
34    Spike_Q183E   97.852474
35    Spike_R408S   97.105509
36    Spike_G142D   96.265173
37    Spike_G252V   95.985061
38  Spike_Y144del   95.985061
39    Spike_N969K   95.798319
40    Spike_Q954H   95.798319
41    Spike_H146Q   85.247432

Omicron Cluster 8:
    Substitution  Percentage
0    Spike_K417N  100.000000
1    Spike_N440K  100.000000
2    Spike_G339D  100.000000
3    Spike_S373P  100.000000
4    Spike_D405N  100.000000
5    Spike_Q498R  100.000000
6    Spike_S371F  100.000000
7    Spike_T376A  100.000000
8    Spike_Y505H  100.000000
9    Spike_N501Y  100.000000
10   Spike_S375F  100.000000
11   Spike_S477N  100.000000
12   Spike_Q493R  100.000000
13   Spike_E484A  100.000000
14   Spike_T478K   99.882284
15   Spike_R408S   99.882284
16   Spike_D614G   99.764567
17   Spike_N764K   99.470277
18   Spike_D796Y   99.293702
19   Spike_H655Y   98.999411
20   Spike_G142D   98.822837
21   Spike_N679K   98.763979
22   Spike_Q954H   97.939965
23   Spike_N969K   97.822248
24   Spike_V213G   96.880518
25    Spike_T19I   96.645085
26   Spike_P681H   95.997646
27  Spike_P25del   90.876986
28  Spike_P26del   90.876986
29  Spike_L24del   90.700412
30    Spike_A27S   90.464979

Omicron Cluster 9:
     Substitution  Percentage
0     Spike_Q498R  100.000000
1     Spike_N501Y  100.000000
2     Spike_Y505H  100.000000
3     Spike_Q493R  100.000000
4     Spike_T478K   99.919094
5     Spike_N440K   99.919094
6     Spike_D614G   99.919094
7     Spike_G339D   99.838188
8     Spike_S373P   99.838188
9     Spike_E484A   99.676375
10    Spike_G446S   99.514563
11    Spike_S375F   99.514563
12    Spike_N679K   99.433657
13    Spike_T547K   99.433657
14    Spike_S477N   99.433657
15    Spike_H655Y   99.352751
16    Spike_G496S   99.271845
17    Spike_R346K   98.705502
18    Spike_K417N   98.462783
19    Spike_N764K   98.462783
20     Spike_T95I   98.220065
21    Spike_S371L   98.058252
22    Spike_G142D   97.815534
23    Spike_D796Y   97.653722
24    Spike_P681H   97.411003
25  Spike_V143del   97.330097
26  Spike_Y144del   97.168285
27  Spike_Y145del   96.844660
28   Spike_H69del   96.763754
29   Spike_V70del   96.601942
30     Spike_A67V   96.521036
31    Spike_N969K   96.116505
32    Spike_Q954H   95.792880
33    Spike_N856K   95.711974
34    Spike_L981F   95.550162
35  Spike_N211del   93.365696
36    Spike_L212I   92.556634

Omicron Cluster 10:
       Substitution  Percentage
0       Spike_N440K  100.000000
1       Spike_T478K  100.000000
2       Spike_Q498R  100.000000
3       Spike_G496S  100.000000
4       Spike_Y505H  100.000000
5       Spike_K417N  100.000000
6       Spike_Q493R  100.000000
7       Spike_S375F  100.000000
8       Spike_E484A   99.914457
9       Spike_S371L   99.914457
10      Spike_D614G   99.828914
11      Spike_S373P   99.743370
12      Spike_G446S   99.743370
13      Spike_S477N   99.657827
14      Spike_N501Y   99.657827
15      Spike_G339D   99.144568
16      Spike_H655Y   98.716852
17      Spike_N679K   98.716852
18      Spike_T547K   98.374679
19      Spike_D796Y   98.032506
20      Spike_N764K   97.861420
21      Spike_G142D   97.604790
22       Spike_T95I   97.433704
23    Spike_V143del   97.433704
24    Spike_Y144del   97.348161
25      Spike_Q954H   97.005988
26       Spike_A67V   97.005988
27    Spike_Y145del   96.920445
28      Spike_N969K   96.834902
29      Spike_P681H   96.150556
30     Spike_H69del   95.722840
31      Spike_L981F   95.637297
32     Spike_V70del   95.551754
33      Spike_N856K   95.551754
34      Spike_L212I   92.386655
35    Spike_N211del   92.386655
36  Spike_ins214EPE   80.325064

Omicron Cluster 11:
    Substitution  Percentage
0    Spike_T376A  100.000000
1    Spike_N440K  100.000000
2    Spike_L452R  100.000000
3    Spike_Q498R  100.000000
4    Spike_S375F  100.000000
5    Spike_S373P   99.879808
6    Spike_S477N   99.879808
7    Spike_D405N   99.879808
8    Spike_N501Y   99.879808
9    Spike_H655Y   99.879808
10   Spike_D614G   99.759615
11   Spike_D796Y   99.639423
12   Spike_N764K   99.639423
13   Spike_Y505H   99.399038
14   Spike_E484A   99.278846
15   Spike_S371F   99.278846
16   Spike_T478K   99.278846
17   Spike_V213G   98.918269
18   Spike_K417N   98.918269
19  Spike_P26del   98.918269
20   Spike_N679K   98.918269
21  Spike_L24del   98.918269
22  Spike_P25del   98.918269
23    Spike_A27S   98.798077
24   Spike_G339D   98.677885
25   Spike_P681H   98.557692
26   Spike_G142D   97.956731
27    Spike_T19I   97.956731
28  Spike_V70del   97.956731
29  Spike_H69del   97.596154
30   Spike_R408S   97.235577
31   Spike_N969K   96.153846
32   Spike_F486V   96.033654
33   Spike_Q954H   95.913462
34   Spike_N460K   95.793269
35   Spike_K444T   95.312500

Omicron Cluster 12:
    Substitution  Percentage
0    Spike_L452R  100.000000
1    Spike_S373P  100.000000
2    Spike_D614G   99.754300
3    Spike_S371F   99.754300
4    Spike_N764K   99.754300
5    Spike_N969K   99.754300
6    Spike_S375F   99.754300
7    Spike_E484A   99.508600
8    Spike_G339D   99.508600
9    Spike_T376A   99.508600
10   Spike_N501Y   99.508600
11   Spike_D796Y   99.262899
12   Spike_Q954H   99.262899
13   Spike_H655Y   99.262899
14   Spike_Y505H   99.017199
15   Spike_T478K   99.017199
16   Spike_S477N   99.017199
17   Spike_D405N   99.017199
18    Spike_T19I   98.771499
19   Spike_P681H   98.771499
20   Spike_N679K   98.771499
21   Spike_V213G   98.771499
22   Spike_F486V   98.525799
23   Spike_Q498R   98.525799
24  Spike_P25del   98.280098
25  Spike_L24del   98.280098
26    Spike_A27S   98.280098
27  Spike_P26del   98.280098
28   Spike_K417N   98.280098
29  Spike_H69del   97.051597
30   Spike_R408S   97.051597
31  Spike_V70del   97.051597
32   Spike_G142D   83.783784

Omicron Cluster 13:
    Substitution  Percentage
0    Spike_N501Y  100.000000
1    Spike_T478K  100.000000
2    Spike_L452R  100.000000
3    Spike_Q498R  100.000000
4    Spike_S371F  100.000000
5    Spike_S373P  100.000000
6    Spike_Y505H  100.000000
7    Spike_D405N  100.000000
8    Spike_E484A  100.000000
9    Spike_S477N  100.000000
10   Spike_T376A  100.000000
11   Spike_F486V   99.968010
12   Spike_N440K   99.968010
13   Spike_R408S   99.968010
14   Spike_D614G   99.936020
15   Spike_G339D   99.904031
16   Spike_S375F   99.840051
17   Spike_K417N   99.840051
18   Spike_N679K   99.264235
19   Spike_D796Y   99.200256
20   Spike_N764K   99.136276
21   Spike_V213G   99.008317
22   Spike_G142D   98.912348
23   Spike_H655Y   98.368522
24  Spike_V70del   98.208573
25   Spike_P681H   98.144594
26  Spike_H69del   98.048624
27  Spike_P26del   97.408829
28  Spike_P25del   97.408829
29  Spike_L24del   97.152911
30    Spike_A27S   96.928983
31   Spike_N969K   96.193218
32   Spike_Q954H   96.001280
33    Spike_T19I   95.745361

In [92]:
# Save to csv
all_cluster_dfs = []

for cluster_name, df in cluster_aa_data.items():
    if cluster_name in [f"Cluster {i}" for i in range(4)]:
        print(cluster_name)
        df['Cluster'] = cluster_name
        df = df[['Cluster', 'Substitution', 'Percentage']]
        all_cluster_dfs.append(df)

combined_df = pd.concat(all_cluster_dfs, ignore_index=True)
combined_df.to_csv('small_omicron_clusters_substitutions.csv', index=False)

print(combined_df)

Cluster 1
Cluster 2
Cluster 3
       Cluster Substitution  Percentage
0    Cluster 1  Spike_S373P  100.000000
1    Cluster 1  Spike_H655Y   99.855908
2    Cluster 1  Spike_S375F   99.855908
3    Cluster 1  Spike_D614G   99.567723
4    Cluster 1  Spike_N501Y   99.567723
..         ...          ...         ...
100  Cluster 3  Spike_N460K   96.272073
101  Cluster 3  Spike_Q954H   95.618051
102  Cluster 3  Spike_K444T   95.356442
103  Cluster 3  Spike_R408S   95.029431
104  Cluster 3  Spike_K417N   94.113800

[105 rows x 3 columns]